-- liquibase formatted sql

--changeset etaradaev:1
CREATE TABLE heroes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_name TEXT NOT NULL,
    attribute VARCHAR
);

--changeset etaradaev:2
ALTER TABLE heroes ADD UNIQUE (hero_name);

--changeset etaradaev:3
ALTER TABLE heroes ADD COLUMN counter_picks TEXT[];